---
- name: 
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & check status
      ansible.builtin.command: sudo bash -c "export PATH=$PATH:/usr/local/bin:/root && kubectl get cores -n instana-core"
      register: status
    - name: show status
      ansible.builtin.debug:
        msg: "{{ status.stdout.split('\n') }}"
#    - name: obtain servicenow incident
#      ansible.builtin.uri:
#        url: https://dev213519.service-now.com/api/now/table/incident?sysparm_query=short_descriptionLIKE{{ sn_query }}&sysparm_limit=10
#        method: GET
#        headers:
#          Content-Type: application/json
#          Accept: application/json
#        user: admin
#        password: -J0crDV2t@Bm
#        return_content: true
#      register: output
