---
- name: Handle MQ events and look up solution
  hosts: localhost
  gather_facts: false

  tasks:
    - name: determine the MQ object
      shell: echo "{{ short_description }}" | awk '{ print $3 }'
      register: MQobject
    - name: show the object
      debug:
        msg: "{{ MQobject }}"
    - name: obtain servicenow knowledge article
      ansible.builtin.uri:
        url: https://dev213519.service-now.com/api/now/table/kb_knowledge?sysparm_query=wikiLIKE{{ MQobject.stdout }}&sysparm_fields=wiki&sysparm_limit=1
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
        user: admin
        password: -J0crDV2t@Bm
        body_format: json
        return_content: true
      register: output
    - name: parse the HTML
      shell: "xmllint --html - | grep -A1 {{ MQobject.stdout }}"
      args:
        stdin: "{{ output.json.result[0].wiki }}"
      register: parsed_html
    - name: show result
      ansible.builtin.debug:
        msg: "{{ parsed_html.stdout_lines }}"
    - name: update incident
      servicenow.itsm.incident:
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
        number: INC0010062
        description: "{{ parsed_html.stdout_lines }}"
