---
- name: Handle MQ events and look up solution
  hosts: localhost
  gather_facts: false

  tasks:
#    - name: Create a new incident
#      servicenow.itsm.incident:
#        # Instance data
#        instance:
#          host: https://dev213519.service-now.com
#          username: admin
#          password: -J0crDV2t@Bm
#        short_description: A00864WOPA for BO.VERK.STORE.001.STOREWF.COWOAVAILABILSVC
#      register: sn_incident
    - name: obtain servicenow knowledge article
      ansible.builtin.uri:
        url: https://dev213519.service-now.com/api/now/table/sn_km_mr_st_kb_knowledge?sysparm_query=short_descriptionLIKEmq&sysparm_fields=content&sysparm_limit=1
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
        user: admin
        password: -J0crDV2t@Bm
        body_format: json
        return_content: true
      register: output
    - name: show result
      ansible.builtin.debug:
        msg: "{{ output.json.result[0].content|split('<br />') }}"
    - name: update incident
      servicenow.itsm.incident:
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
        number: "{{ sn_incident }}"
        description: "{{ output.json.result[0].content.split('<br />') }}"
