---
- name: Sample playbook
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.slurp:
        src: /home/itzuser/postgres.yaml
      register: postgres
    - name: cat file
      ansible.builtin.command: cat /home/itzuser/postgres.yaml
      register: catfile
    #- name: Print returned information
    #  ansible.builtin.debug:
    #    msg: "the value of foo.txt is {{ lookup('ansible.builtin.file', 'postgres') }}"
    - name: update incident
      servicenow.itsm.incident:
        # Instance data
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
        number: "{{ sn_incident }}"
        state: scheduled
        short_description: "{{ sn_description }}"
        description: "{{ catfile }}"
        impact: high
        urgency: high
      register: result
