---
- name: Sample playbook
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.fetch:
        src: /home/itzuser/postgres.yaml
        dest: postgres.yaml
        flat: yes
    - name: Print returned information
      ansible.builtin.debug:
        msg: "the value of foo.txt is {{ lookup('ansible.builtin.file', 'postgres.yaml') }}"
