---
- name: Sample playbook
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.fetch:
        src: /home/itzuser/postgres.yaml
        result: postgres
    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ postgres['content'] }}"
