---
- name: Sample playbook
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.fetch:
        src: /home/itzuser/postgres.yaml
        dest: postgres.yaml
        register: postgres
    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', 'postgres.yaml') }}"
    - name: update incident
      servicenow.itsm.incident:
        # Instance data
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
        number: INC0010001
        state: scheduled
        description: "{{ postgres['content'] }}"
        impact: high
        urgency: high
      register: result
