---
- name: Sample playbook
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.command: cat /home/itzuser/postgres.yaml
      register: catfile
    - name: update incident
      servicenow.itsm.incident:
        # Instance data
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
        number: "{{ sn_incident }}"
        state: "{{ sn_state }}"
        short_description: "{{ sn_description }}"
        description: "{{ catfile }}"
