---
- name: Linux Batch Job
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.command: cat /tmp/VR2024.LOG_01iwva_00001
      register: catfile
    - name: obtain servicenow incident
      ansible.builtin.uri:
        url: https://dev213519.service-now.com/api/now/table/incident?sysparm_query=short_description%3D{{ sn_query }}&sysparm_limit=1
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
        user: admin
        password: -J0crDV2t@Bm
        return_content: true
      register: output
    - name: show incident number
      ansible.builtin.debug:
        msg: "{{ output.json.result[0].number }}"
      register: sn_incident
    - name: update incident
      servicenow.itsm.incident:
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
        number: "{{ sn_incident }}"
        state: "{{ sn_state }}"
        short_description: "{{ sn_query }}"
        description: "{{ catfile }}"
