---
- name: Sample playbook
  hosts: cloudvsi
  gather_facts: false

  tasks:
    - name: connect to system & get log file
      ansible.builtin.fetch:
        src: /home/itzuser/postgres.yaml
        dest: /home/itzuser/postgres.yaml
        flat: yes
    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ /home/itzuser/postgres.yaml['content'] }}"
