---
- name: Sample playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a new incident
      servicenow.itsm.incident:
        # Instance data
        instance:
          host: https://dev213519.service-now.com
          username: admin
          password: -J0crDV2t@Bm
