---

- name: Query incidents and update
  hosts: localhost
  gather_facts: false

  tasks:
   - name: obtain servicenow knowledge
     ansible.builtin.uri:
       url: https://dev213519.service-now.com/api/now/table/incident?sysparm_query=short_description%3DInconsistent%20Data&sysparm_limit=1
       method: GET
       headers:
         Content-Type: application/json
         Accept: application/json
       user: admin
       password: -J0crDV2t@Bm
     register: result
  - name: Create a new incident
    servicenow.itsm.incident:
    # Instance data
    instance:
      host: https://dev213519.service-now.com
      username: admin
      password: -J0crDV2t@Bm
