---
- name: Query incidents and update
  hosts: localhost
  gather_facts: false

  tasks:
  - name: obtain servicenow incident
    ansible.builtin.uri:
      url: https://dev213519.service-now.com/api/now/table/incident?sysparm_query=short_description%3DInconsistent%20Data&sysparm_limit=1
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      user: admin
      password: -J0crDV2t@Bm
      return_content: true
    register: result
  - name: show results
    ansible.builtin.debug:
      msg: "{{ result.content.result[0].number }}"
